//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE_EVENT
    {
        public long ID { get; set; }
        public long SOURCE_FILE_ID { get; set; }
        public long TARGET_FILE_ID { get; set; }
        public long PROCESS_ID { get; set; }
        public System.DateTime START_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public FILE_EVENT_TYPE_ENUM TYPE { get; set; }
        public long COUNT { get; set; }
    
        public virtual FILE FILE { get; set; }
        public virtual FILE FILE1 { get; set; }
        public virtual PROCESS PROCESS { get; set; }
    }
}
