//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE
    {
        public FILE()
        {
            this.FILE_EVENT = new HashSet<FILE_EVENT>();
            this.FILE_EVENT1 = new HashSet<FILE_EVENT>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public long COMPUTER_ID { get; set; }
        public long USER_ID { get; set; }
        public long EXTENSION_ID { get; set; }
    
        public virtual COMPUTER COMPUTER { get; set; }
        public virtual EXTENSION EXTENSION { get; set; }
        public virtual ICollection<FILE_EVENT> FILE_EVENT { get; set; }
        public virtual ICollection<FILE_EVENT> FILE_EVENT1 { get; set; }
        public virtual USER USER { get; set; }
    }
}
