//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DataModel
{
    using System;
    
    public enum FILE_EVENT_TYPE_ENUM : byte
    {
        Unknown = 0,
        CreateFile = 1,
        ReadFile = 2,
        RenameMoveFile = 3,
        WriteFile = 4,
        DeleteFile = 5
    }
}
