//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_SETTING
    {
        public GROUP_SETTING()
        {
            this.USER_GROUP = new HashSet<USER_GROUP>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public System.TimeSpan ACCUMULATION_INTERVAL { get; set; }
        public System.TimeSpan FILTER_UPDATE_INTERVAL { get; set; }
        public System.TimeSpan GRANULARITY { get; set; }
        public bool COLLECT_PROCESSES { get; set; }
        public bool COLLECT_EXTENSIONS { get; set; }
    
        public virtual ICollection<USER_GROUP> USER_GROUP { get; set; }
    }
}
