//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS
    {
        public PROCESS()
        {
            this.FILE_EVENT = new HashSet<FILE_EVENT>();
            this.USER_GROUP = new HashSet<USER_GROUP>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<FILE_EVENT> FILE_EVENT { get; set; }
        public virtual ICollection<USER_GROUP> USER_GROUP { get; set; }
    }
}
