//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.FILE = new HashSet<FILE>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public long DOMAIN_ID { get; set; }
        public long USER_GROUP_ID { get; set; }
    
        public virtual DOMAIN DOMAIN { get; set; }
        public virtual ICollection<FILE> FILE { get; set; }
        public virtual USER_GROUP USER_GROUP { get; set; }
    }
}
